Adding French options
alexcodito/HelloFreshCrawler pull request #8
Opened 2024-08-20 18:44 UTC by AlxFrst

- Added "FR" as a locale choice in index.js
- Updated locale handling in hello-fresh.js for "FR" locale

2024-08-20 18:52 UTC, alexcodito requested changes
Thank you for raising this PR. I've added a few comments.

2024-08-20 18:52 UTC, alexcodito commented on index.js
> +
Please remove the redundant new line

2024-08-20 18:52 UTC, alexcodito commented on services/hello-fresh.js
> +      apiSearchParams.locale = `fr-${settings.locale.toUpperCase()}`; // Gestion de la locale FR
Please remove the comment in French

2024-08-20 19:04 UTC, alexcodito commented
Please also list FR in the README.md file.

2024-08-20 19:05 UTC, alexcodito requested changes
Please also list FR in the README.md file.

2024-10-28 23:32 UTC, AlxFrst commented
Completed, sorry for errors :)

2024-11-02 19:36 UTC, alexcodito approved these changes

2024-11-02 19:36 UTC, merged